alpacahq/marketstore

- contrib/ondiskagg/ondiskagg.go
- executor/wal.go
Actually re-use the file pointer...
> File pointer fix

- catalog/catalog.go
And minor cleanup.  The lock protocol was simply broken.
> Fix lock protocol around catalog category list

- .circleci/config.yml
- Makefile
Images will be deployed to versioned tags.
> Versioned deployment

- .circleci/config.yml
> setup_remote_docker

- executor/wal.go
- executor/writtenIndexes.go
- executor/writtenIndexes_test.go
running the triggers sequentially was taking too long
> fire triggers in parallel

- frontend/client/client.go
Shouldn't care if BaseURL has trailing /
> Add / to rpc client

- Gopkg.lock
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/slait/slait.go
- executor/writer.go
- utils/io/all_test.go
- utils/io/datashape.go
Addresses: https://github.com/alpacahq/marketstore/issues/38
> Verify DataShape before write

- contrib/slait/slait.go
- contrib/slait/slait_test.go
Now buffering writes so the socket doesn't get overwhelmed.
> Fix slait plugin lag

- .circleci/config.yml
- Dockerfile
- contrib/slait/slait.go
- executor/readvariable.go
addresses: https://github.com/alpacahq/marketstore/issues/48
> go 1.10 upgrade

- cmd/tools/mkts/main.go
Addresses: https://github.com/alpacahq/marketstore/issues/43
> mkts load panic fix

- Dockerfile
- Gopkg.lock
- entrypoint.sh
For specifying a user inside the docker container.
> Add entrypoint to Dockerfile

- Dockerfile
- cmd/marketstore/marketstore.go
Calls marketstore instead of UT, and default config file is mkts.yml as in repo.
> Fix Dockerfile CMD

- Dockerfile
> golang v1.10.3

- Gopkg.lock
- Makefile
- contrib/polygon/Makefile
- contrib/polygon/README.md
- contrib/polygon/api/api.go
- contrib/polygon/polygon.go
- mkts.yml
A plugin for polygon's data API (https://polygon.io)
> polygon plugin

- contrib/polygon/api/api.go
- contrib/polygon/polygon.go
Subscribe only to what is needed.
> cleanup polygon plugin symbol list support

- contrib/polygon/polygon.go
Added query_start parameter to specify where to start backfilling from rather than just the previously written record. Also made the backfilling run in parallel. It is currently spinning 10 goroutines per core on the system, which should be fine since most of the time it will be just waiting on HTTP responses.
> polygon backfilling improvements

- contrib/polygon/polygon.go
Extraneous logs & empty response handling.
> polygon plugin cleanup

- README.md
Just added an example of what a correct output of what running marketstore looks like and added a command which helped me run marketstore and might help interested contributors.
> Clarify Usage Section

- README.md
Fix issue Hitoshi raised: https://github.com/alpacahq/marketstore/pull/83
> Updated Readme with more clear description of docker command

- cmd/tools/mkts/main.go
- frontend/client/client.go
- frontend/query.go
- frontend/query_test.go
Realized the RPC client didn't support ListSymbols even though it is clearly defined in the documentation as being supported.
> DataService.ListSymbols client support

- contrib/binancefeeder/binancefeeder_test.go
Fixed unit test API binance symbols issue.
> Removed API unit test since that makes no sense

- Gopkg.lock
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/ondiskagg/aggtrigger/util.go
- utils/io/all_test.go
- utils/io/columnseries.go
After some extensive testing, the issue in the previous optimization was found. Current implementation has been tested for both large backfills, as well as live stream appending, and is working well.
> aggtrigger optimization v2

- contrib/binancefeeder/binancefeeder.go
Changed so that the data is collected to the very end of what is explicitly set as queryEnd
> Sets timeEnd to Time.now() if it is larger than the current time

- contrib/polygon/README.md
- contrib/polygon/api/api.go
- contrib/polygon/polygon.go
allows users to specify nats cluster to connect to
> configurable nats servers (polygon plugin)

- contrib/binancefeeder/binancefeeder.go
Fix overwriting by:
- Removing incomplete candle when writing
- Ensure that you wait till the next :00 time
> Fix binancefeeder overwriting and overcalling issues

- go.mod
- go.sum
now that the author has fixed this, let's use the master branch
> antlr4 dependency fix

- utils/io/keytypes.go
> timeframe nil check fix

- contrib/ondiskagg/aggtrigger/accum.go
- contrib/ondiskagg/aggtrigger/functions/first.go
- contrib/ondiskagg/aggtrigger/functions/last.go
- contrib/ondiskagg/aggtrigger/functions/max.go
- contrib/ondiskagg/aggtrigger/functions/min.go
- contrib/ondiskagg/aggtrigger/functions/sum.go
Addresses: https://github.com/alpacahq/marketstore/issues/101
> aggtrigger type support improvement

- cmd/start/main.go
- frontend/utilities.go
- frontend/utilities_test.go
profiling & heartbeat can be served together as utilities
> consolidate utility endpoints

- contrib/stream/shelf/shelf.go
- contrib/stream/shelf/shelf_test.go
- contrib/stream/streamtrigger/streamtrigger.go
Because keys were pointers, replacement wasn't working correctly, so stream map was growing unnecessarily. Cleaned up and added unit test.
> streamtrigger replacement fix

- .circleci/config.yml
- tests/integ/Makefile
- tests/integ/README.md
- tests/integ/dockerfiles/Makefile.common
- tests/integ/dockerfiles/pyclient/requirements.txt
- tests/integ/tests/test_ticks.py
- modify the integration test for TICK
- update Circle CI config and Makefile to run the integration test
> Integration Test for TICK

- Makefile
- contrib/binancefeeder/Makefile
- contrib/bitmexfeeder/Makefile
- contrib/gdaxfeeder/Makefile
- contrib/iex/Makefile
- contrib/ondiskagg/Makefile
- contrib/polygon/Makefile
- contrib/slait/Makefile
- contrib/stream/Makefile
These were the necessary changes to get it working with GoLand's built-in debugger
> add `make debug` command for building with debug info included

- Dockerfile
- contrib/iex/Makefile
- for BUILD : use golang:buster which is including glibc
- for RUN : use alpine. It works if libc6-compat library is installed
> Dockerfile improvement

- contrib/xignitefeeder/api/model.go
- contrib/xignitefeeder/writer/quotes_range_writer.go
- contrib/xignitefeeder/writer/quotes_writer.go
This Pull Request is to add some columns to data stored to marketstore by Xignite Feeder Plugin
> [XigniteFeeder Plugin] add some feed data

- contrib/xignitefeeder/api/model.go
- contrib/xignitefeeder/writer/quotes_range_writer.go
- contrib/xignitefeeder/writer/quotes_writer.go
Reverts alpacahq/marketstore#256
> Revert "[XigniteFeeder Plugin] add some feed data"

- contrib/xignitefeeder/README.md
- contrib/xignitefeeder/api/client.go
- contrib/xignitefeeder/api/client_test.go
- contrib/xignitefeeder/api/model.go
- contrib/xignitefeeder/configs/config.go
- contrib/xignitefeeder/feed/backfill.go
- contrib/xignitefeeder/feed/backfill_test.go
- contrib/xignitefeeder/internal/mocks.go
- contrib/xignitefeeder/symbols/manager.go
- contrib/xignitefeeder/writer/quotes_range_writer.go
- contrib/xignitefeeder/writer/quotes_range_writer_test.go
- contrib/xignitefeeder/xignitefeeder.go
- go.mod
- go.sum
Reverts alpacahq/marketstore#259
> Revert "Revert "Xignite feeder index symbols""

- .circleci/config.yml
- .codecov.yml
- .gitignore
- Makefile
- README.md
- contrib/bitmexfeeder/api/api_test.go
Hi marketstore admin, could one of you follow the steps to enable codecov?
Thank you in advance!
1. Go to 
https://codecov.io/gh/alpacahq/marketstore
, enable codecov and get CODECOV_TOKEN
2. Go to 
https://circleci.com/gh/alpacahq/marketstore
3. Click the setting icon (=gear icon)
4. Click "Environmental Variables"
5. Click "Add Variable"and Set name: CODECOV_TOKEN , value: the token value you get at the step 1
6. I will rebuild this PR
> enable codecov

- executor/scanner.go
packingReader is the most time-consuming part in Query API.
this tiny PR improves the query response time for a 1Sec-timeframe bucket by 10%.
This branch:
```
$ msbench --write-num=1 --query-num=100 --timeframes=1Sec --range=1year --limit=""
timeframe, elapsed_time_per_operation(write/query)
[is_variable_length=False, data_size=100]
1Sec   24.13967ms/write
1Sec   137.91687ms/query
[is_variable_length=True, data_size=100]
1Sec   27.35185ms/write
1Sec   150.87722ms/query
```
master branch:
```
$ msbench --write-num=1 --query-num=100 --timeframes=1Sec --range=1year --limit=""
timeframe, elapsed_time_per_operation(write/query)
[is_variable_length=False, data_size=100]
1Sec   25.22351ms/write
1Sec   157.51265ms/query
[is_variable_length=True, data_size=100]
1Sec   27.45766ms/write
1Sec …
```
> peformance improvement for packingReader function

- Dockerfile
- go.mod
This PR also addresses the module loading issue discovered during polyfeed testing.
> Bump golang to v1.14

- helm-chart/.helmignore
- helm-chart/Chart.yaml
- helm-chart/templates/_helpers.tpl
- helm-chart/templates/configmap.yaml
- helm-chart/templates/ingress.yaml
- helm-chart/templates/service.yaml
- helm-chart/templates/serviceaccount.yaml
- helm-chart/templates/statefulset.yaml
- helm-chart/values.yaml
Run MarketStore as StatefulSet in Kubernetes. 
Tested with Helm 3.2.0-rc1.
> K8S Support: Add helm-chart

- tests/integ/dockerfiles/pyclient/requirements.txt
integration-test job is failing on master branch, let me update the pymarketstore version...
> fix: update pymarketstore version for integration-test

- executor/wal.go
refactor WALFile struct by removing a function from WALFile struct to improve testability
> refactor: remove a function from WalFile struct

- executor/wal.go
- executor/writer.go
remove some functions from walfile struct to improve testability
> refactor: remove functions from walfile struct

- executor/wal.go
> refactor: move the parse logic out of the replay function

- contrib/polygon/api/api.go
- contrib/polygon/backfill/backfiller/backfiller.go
To support backfill of larger set of symbols, based on glob patterns.
> ENH: polygon backfill glob filter

- cmd/start/main.go
- utils/config.go
Server-side version of https://github.com/alpacahq/pymarketstore/pull/54
> allow configuring gRPC message size limits

- Makefile
- contrib/iex/Makefile
- contrib/xignitefeeder/Makefile
* fix the `make debug` command
* add missing `make install` command
* separate running `go generate` from sqlparser stuffs (adds`make generate-sql` command)
> fix Makefiles

- executor/wal.go
- utils/io/serializer.go
to make FlushToWAL function simpler
> refactor: serialize Transaction Group function

- catalog/catalog.go
- utils/io/metadata.go
- move some inner functions out
- change lines for visibility
> fix: small refactor in catalog

- executor/all_test.go
- executor/cache.go
- executor/wal.go
- executor/wal/oib.go
- executor/wal/wt.go
- executor/writer.go
- utils/io/columnseries.go
WHAT
- add comments
- change some variable names
- [logic change] increment when a new Transaction Group ID is issued
WHY
- refactor
- after this PR, we will release Replication feature. We want to use Transaction Group ID as an ID to tell the master position to replica instances.
> fix: add comments, change variable names, increment TGID logic

- cmd/start/main.go
- executor/writer.go
- frontend/server.go
- frontend/stream/stream.go
- helm-chart/templates/servicemonitor.yaml
- helm-chart/values.yaml
- metrics/metrics.go
New metrics:
- Startup duration
- RPC request histogram(s)
- WriteCSM histogram
> Prometheus metrics

- utils/io/all_test.go
- utils/io/generics.go
- remove unused implementation `Quorum`
- code maintenance
> refactor: remove unused implementation

- executor/writer.go
- go.mod
- tests/integ/tests/test_coerce_column.py
- utils/io/columnseries.go
- utils/io/generics.go
After merging [this PR](https://github.com/alpacahq/marketstore/pull/363), I noticed that there is no integration test for Coerce Column feature
> Integration test for Coerce Column feature

- tests/integ/dockerfiles/pyclient/requirements.txt
- tests/integ/tests/test_create.py
- add some integration tests for Create API
- Create API is enabled recently and there was no test for it
> add: integration test for Create endpoint

- cmd/connect/session/client.go
- cmd/connect/session/create.go
- cmd/connect/session/create_test.go
- add unit tests for `\create` command of marketstore CLI
- for better test coverage
> Unit test for \create command

- frontend/query.go
- a small refactor for Query function
> refactor: separate executeSQL function

- catalog/catalog.go
- catalog/catalog_test.go
- catalog/errors.go
- executor/all_test.go
- executor/instance.go
- executor/writer.go
- planner/planner_test.go
In catalog package,
- add error handling
- remove anonymous function
> refactor: error handling for catalog package

- executor/writer.go
small refactor to remove some code that is using `ThisInstance` singleton config instance to improve testability
> refactor: avoid singleton config instance

- executor/all_test.go
- executor/cache.go
- executor/instance.go
- executor/wal.go
- add error handling to Instance Config setup
- simplify WALByPass logic
> refactor: error handling of instance.go and constructor of wal

- executor/all_test.go
in all_test.go, use `testing.T` instead of Test Suite 
to make each test more independent
> refactor(all_test): use testing.T instead of TestSuite

- executor/wal.go
- executor/writer.go
make writer struct not to touch the filepath of WAL file
refactor
> refactor: writer struct doesn't touch wal.FilePath

- cmd/start/main.go
- executor/writer.go
- executor/writer_err.go
- frontend/server.go
- replication/replay.go
- make "ErrorWriter" struct and Writer interface to implement the logic that Write fails on Replica instance using the interface/implementation
- refactor using DI
> refactor: implement error writer using interface

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- frontend/grpc.go
- frontend/query.go
- frontend/query_test.go
- frontend/server.go
- frontend/server_test.go
- frontend/write_test.go
- add QueryService struct and its interface
- refactor. inject Query logic to Data Service to improve testability.
> add: QueryService and its interface

- tests/integ/dockerfiles/pyclient/requirements.txt
- tests/integ/tests/test_aggfunc.py
integration test for AVG/MIN/MAX/COUNT/GAP aggregator functions
To ensure that the future refactoring of the aggregator functions doesn't break the compatibility
> add: integ test for aggfunc

- tests/integ/tests/test_aggcandler.py
add integration test for CandleCandler and TickCandler agg functions
internal refactoring of Agg func implementation will be done after this PR and the tests will be used to ensure the compatibility before and after the refactor
> add: integ test for candler agg funcs

- contrib/candler/candlecandler/all_test.go
- contrib/candler/candlecandler/candlecandler.go
- contrib/candler/candler.go
- contrib/candler/tickcandler/all_test.go
- contrib/candler/tickcandler/tickcandler.go
- frontend/query.go
- sqlparser/all_test.go
- sqlparser/selectrelation.go
- uda/adjust/adjust.go
- uda/adjust/adjust_test.go
- uda/avg/avg.go
- uda/count/count.go
- uda/datatypes.go
- uda/gap/gap.go
- uda/max/max.go
- uda/min/min.go
- merge `Init` and `New` functions of AggFunc interface
- for better testability and simplicity
> fix(aggfunc): merge Init and New function

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/candlecandler/candlecandler.go
- contrib/candler/tickcandler/all_test.go
- contrib/candler/tickcandler/tickcandler.go
- frontend/grpc.go
- frontend/query.go
- frontend/query_test.go
- frontend/server.go
- frontend/server_test.go
- frontend/write_test.go
- sqlparser/all_test.go
- sqlparser/executablestatement.go
- sqlparser/insertintostatement.go
- sqlparser/registry.go
- sqlparser/selectrelation.go
- uda/adjust/adjust.go
- uda/adjust/adjust_test.go
- uda/avg/avg.go
- uda/count/count.go
- uda/datatypes.go
- uda/gap/gap.go
- uda/max/max.go
- uda/min/min.go
- inject Aggrefactor functions to its dependent modules
- to improve unittest-ability of marketstore
> Dependency injection of Aggregator Function

- catalog/catalog.go
- catalog/catalog_test.go
- executor/scanner.go
- utils/io/metadata.go
lint issues found during code reading
> refactor: small lint issues

- catalog/catalog_test.go
- cmd/connect/loader/all_test.go
- cmd/connect/loader/utils.go
- contrib/stream/stream.go
- frontend/stream/stream.go
small refactor for lint issues
> fix: lint issues

- executor/writer.go
##WHAT
- same as title
- `root` looks like a string of the root directory or a name of a super user
> chore: rename root to rootCatDir

- catalog/catalog.go
- cmd/connect/session/client.go
- contrib/ice/sirs/collect.go
- contrib/stream/streamtrigger/streamtrigger.go
- executor/scanner.go
- executor/wal_test.go
- planner/planner_test.go
- sqlparser/interpreter.go
- tests/integ/tests/test_bug_duplicated_limit.py
- utils/io/misc.go
- utils/timeframe.go
same as title
refactor and add golangci-lint check in CI in the near future for better code quality
> fix: random lint issues

- executor/cachedfp.go
- executor/wal.go
- executor/walreplay.go
- add error handlings to WAL process
- refactor by early return
- refactor
> refactor(wal): error handling and early return

- cmd/connect/session/create.go
- cmd/connect/session/create_test.go
##WHAT
- fix a possible panicking issue in the remoteAPIclient implementation
##WHY
- remoteAPIClient.GetInfo causes a panic during CSV load
> fix(remoteAPIClient): fix a possible panic in remoteAPIClient.GetInfo

- README.ja.md
- README.md
- Fix package link in Japanese documentation.
- Fix grammar issues in English documentation.
> Fixes to documentation

- contrib/xignitefeeder/api/client.go
- contrib/xignitefeeder/api/client_test.go
- contrib/xignitefeeder/api/model.go
- contrib/xignitefeeder/symbols/manager.go
- add error logs for Xignite Feeder plugin
- for better error monitoring
> refactor(xignite): add error logs

- contrib/alpacabkfeeder/writer/bar_writer_test.go
fix the unit-test failure on master branch
> fix(alpacabkfeeder): unit test bug

- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- executor/writer.go
- plugins/trigger/trigger_test.go
- utils/io/all_test.go
- utils/io/anyset_test.go
- utils/io/columnseries.go
add some error handling for an error that was ignored
> fix: add error handling in Column Coercion impl

- cmd/connect/session/remote_api_client_test.go
- contrib/binancefeeder/binancefeeder.go
- contrib/bitmexfeeder/api/api.go
- contrib/bitmexfeeder/bitmexfeeder_test.go
- contrib/calendar/calendar.go
- contrib/candler/candler.go
- contrib/candler/tickcandler/all_test.go
- contrib/gdaxfeeder/gdaxfeeder.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/api/api.go
- contrib/xignitefeeder/api/client.go
- executor/all_test.go
- executor/buffile/buffile_test.go
- executor/wal_test.go
- frontend/client/client.go
- frontend/query.go
- frontend/stream/stream_test.go
- planner/planner.go
- planner/planner_test.go
- replication/receiver_test.go
- replication/replay_test.go
- tests/integ/tests/test_no_data_available.py
- tests/replication/tests/test_write.py
- uda/adjust/caloader.go
- uda/min/min.go
- utils/io/all_test.go
- utils/io/columnseries.go
- utils/rpc/msgpack2/msgpack_test.go
- utils/test/setup.go
after fixing lint issues, enable linter for CI
> fix: some lint issues

- contrib/alpacabkfeeder/feed/backfill_test.go
- contrib/xignitefeeder/feed/time_checker.go
- executor/cachedfp.go
- executor/delete.go
- executor/errors.go
- executor/instance.go
- executor/readvariable.go
- executor/rewritebuffer.go
- executor/scanner.go
- executor/wal.go
- executor/walreplay.go
- executor/writer.go
- replication/grpc_server.go
- replication/retry.go
- replication/retry_test.go
- replication/sender.go
- utils/config.go
- utils/timeframe.go
> fix lint issues

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- contrib/alpaca/handlers/handlers_test.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/tickcandler/all_test.go
- contrib/ice/cmd/reorg/import.go
- contrib/ice/cmd/reorg/show.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/polygon/handlers/handlers_test.go
- executor/all_test.go
- executor/instance.go
- frontend/query_test.go
- frontend/stream/stream_test.go
- sqlparser/all_test.go
- uda/adjust/adjust_test.go
implement function option pattern in InstanceMetadata struct
> refactor(instancemetadata): function option pattern

- cmd/connect/loader/time.go
- cmd/connect/loader/utils.go
- cmd/connect/loader/write.go
- sqlparser/buildVisitorCode.sh
- sqlparser/sqlparsetree.go
- sqlparser/visitorcodegenerated.go
fix lint issues and add some coments
> refactor: lint issues and add comments

- cmd/start/main.go
- contrib/ice/reorg/record_test.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- executor/all_test.go
- frontend/grpc.go
- frontend/utilities.go
- uda/adjust/caloader.go
- utils/test/setup.go
fix some lint issues found by errcheck linter
> fix: errcheck lint issues

- catalog/catalog.go
- cmd/connect/session/load.go
- cmd/start/main.go
- contrib/alpacabkfeeder/configs/config.go
- contrib/binancefeeder/binancefeeder.go
- contrib/bitmexfeeder/api/api.go
- contrib/iex/api/api.go
- contrib/polygon/api/api.go
- contrib/polygon/polygon.go
- contrib/polyiex/api/api.go
- contrib/xignitefeeder/configs/config.go
- executor/delete.go
- executor/scanner.go
- executor/walreplay.go
- frontend/grpc.go
- frontend/query.go
- frontend/server.go
- utils/io/generics.go
> fix(lint): govet

- contrib/calendar/calendar.go
- contrib/calendar/calendar_test.go
- contrib/ice/reorg/convert.go
- contrib/polygon/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/polygon/handlers/handlers.go
- contrib/polygon/polygon.go
- utils/io/metadata.go
fix a part of gomnd linter issues
> fix(lint): gomnd issues

- contrib/alpacabkfeeder/symbols/manager.go
- contrib/alpacabkfeeder/timer/timer.go
- contrib/binancefeeder/binancefeeder.go
- contrib/stream/shelf/shelf.go
- contrib/xignitefeeder/timer/timer.go
- docs/design/durable_writes_design.txt
- executor/scanner.go
- executor/wal.go
- executor/wal/file.go
- executor/walreplay.go
- utils/config.go
- utils/functions/datatypes.go
- utils/io/columnseries.go
- utils/io/metadata.go
- utils/test/setup.go
- utils/timeframe.go
> fix: gosimple and other lint issues

- catalog/errors.go
- cmd/estimate/main.go
- executor/rewritebuffer.go
- executor/wal.go
- executor/wal/errors.go
- executor/walclean.go
- metrics/du.go
- planner/planner.go
- uda/gap/gap.go
- utils/config.go
- utils/io/keytypes.go
- utils/rpc/msgpack2/server.go
- utils/timeframe.go
fix some linter issue found by `gomnd`
> fix: gomnd linter issues

- contrib/polygon/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/xignitefeeder/api/client.go
- contrib/xignitefeeder/api/client_test.go
- contrib/xignitefeeder/feed/backfill.go
- contrib/xignitefeeder/feed/backfill_test.go
- contrib/xignitefeeder/feed/recent_backfill.go
- contrib/xignitefeeder/feed/recent_backfill_test.go
- contrib/xignitefeeder/feed/worker.go
- contrib/xignitefeeder/feed/worker_test.go
- contrib/xignitefeeder/internal/mocks.go
- contrib/xignitefeeder/symbols/manager.go
- contrib/xignitefeeder/symbols/manager_test.go
- contrib/xignitefeeder/timer/timer.go
- contrib/xignitefeeder/xignitefeeder.go
- uda/adjust/caloader.go
- utils/io/byteconversions.go
> fix(lint): noctx & lll linter issues

- contrib/bitmexfeeder/bitmexfeeder_test.go
- contrib/gdaxfeeder/gdaxfeeder_test.go
- contrib/polyiex/handlers/handlers.go
- executor/all_test.go
- executor/wal_test.go
- executor/written_test.go
- frontend/stream/stream.go
- uda/adjust/adjust_test.go
- uda/adjust/caloader.go
- uda/gap/gap.go
- utils/io/all_test.go
- utils/io/byteconversions.go
- utils/io/rowseries.go
fixed some forcetypeassert linter issues
> fix(lint): forcetypeassert check

- catalog/catalog.go
- catalog/catalog_test.go
- cmd/connect/loader/utils.go
- cmd/connect/loader/write.go
- contrib/alpaca/alpaca.go
- contrib/alpaca/api/connection.go
- contrib/alpaca/api/websocket.go
- contrib/binancefeeder/binancefeeder.go
- contrib/ice/reorg/announcement.go
- contrib/ice/reorg/convert.go
- contrib/polygon/backfill/backfill.go
- contrib/polyiex/handlers/handlers.go
- contrib/stream/streamtrigger/streamtrigger.go
- contrib/xignitefeeder/feed/backfill.go
- contrib/xignitefeeder/writer/quotes_writer.go
- executor/wal.go
- executor/wal/file.go
- frontend/stream/stream_test.go
- models/bar.go
- models/quote.go
- models/trade.go
- replication/retry.go
- uda/adjust/adjust_test.go
- uda/adjust/caloader_test.go
- utils/functions/datatypes.go
- utils/io/all_test.go
- utils/io/datashape.go
- utils/io/rowseries.go
- utils/timeframe.go
fix all the `gocritic` linter issues
> fix(lint): gocritic issues

- contrib/alpacabkfeeder/README.md
- add how to update Alpaca API client timeout
> fix(alpacabkfeeder): update readme

- cmd/connect/loader/utils.go
- cmd/connect/loader/write.go
- cmd/connect/session/client.go
- cmd/start/main.go
- contrib/alpaca/api/websocket.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/polygon/api/api.go
- contrib/polygon/api/websocket.go
- executor/all_test.go
- executor/buffile/buffile.go
- executor/scanner.go
- executor/wal.go
- executor/wal_test.go
- executor/writer.go
- frontend/client/client.go
- plugins/trigger/trigger.go
- plugins/trigger/trigger_test.go
- sqlparser/selectrelation.go
- utils/io/all_test.go
- utils/io/byteconversions.go
- utils/io/coercecolumn.go
- utils/io/coercecolumn_test.go
- utils/io/columnseries.go
- utils/io/generics.go
- utils/io/metadata.go
- utils/pool/pool.go
- utils/pool/pool_test.go
- remove GetByName function because GetColumn function does the same thing
- separate wal.WriteBuffer process by record type to remove type assertions
- random small lint fixes
> [draft] fix: random lint issues

- cmd/connect/session/client.go
- cmd/connect/session/create.go
- cmd/connect/session/create_test.go
- cmd/connect/session/help.go
- cmd/connect/session/load.go
- cmd/connect/session/show.go
- cmd/connect/session/sql.go
- cmd/connect/session/trim.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/polygon/api/connection.go
- frontend/client/client.go
- utils/log/log.go
- utils/rpc/msgpack2/client.go
- utils/rpc/msgpack2/msgpack_test.go
- fix lint issues related to marketstore CLI
> fix: lint issues for the command line interface

- utils/config.go
> fix: remove cluster_mode config

- README.ja.md
- README.md
- cmd/create/default.yml
- contrib/alpaca/mkts.example.yml
- contrib/iex/mkts.example.yml
- contrib/polygon/mkts.example.yml
- examples/deprecated/testdir.yaml
- tests/integ/bin/mkts.yml
- tests/replication/config/mkts-master.yml
- tests/replication/config/mkts-replica.yml
- utils/config.go
> fix: remove queryable config

- cmd/connect/loader/utils.go
- contrib/binancefeeder/binancefeeder.go
- contrib/ondiskagg/aggtrigger/accum.go
- contrib/stream/streamtrigger/streamtrigger.go
- executor/wal.go
- frontend/query_test.go
- internal/di/replication.go
- utils/io/metadata.go
- refactor for fixing lint issues
> fix(lint): refactor accumFunc mapping

- contrib/xignitefeeder/README.md
- contrib/xignitefeeder/configs/config.go
- contrib/xignitefeeder/configs/config_test.go
- contrib/xignitefeeder/configs/envconfig.go
- contrib/xignitefeeder/symbols/manager.go
- contrib/xignitefeeder/xignitefeeder.go
- a feature to exclude specified stocks
- please read contrib/xignitefeeder/README.md for the usage
> feat(xignitefeeder): NotQuoteStockList feature

- contrib/alpacabkfeeder/alpacav2.go
> fix: minor logging fix
