- catalog/catalog.go
- cmd/tools/integritycheck/integritycheck.go
- executor/scanner.go
- utils/io/all_test.go
- utils/io/metadata.go
The previous flag check wasn't safe for concurrency.  I tried
sync.Mutex, but didn't work due to the Go's memory model and ended up
with sync.Once solution.  There are still a few places where it updates
fields when reading it, which is not a very good idea anyway, but leave
it for now since they are minor use cases at the moment.
> Fix (most) race conditions in TimeBucketInfo using sync.Once

- SQLParser/insertintostatement.go
- catalog/catalog.go
- catalog/catalog_test.go
- cmd/tools/mkts/main.go
- contrib/candler/tickcandler/all_test.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- executor/all_test.go
- executor/writer.go
- frontend/query.go
- planner/planner.go
NewWriter now only requires a TimeBucketInfo to write to disk. This, along with the concurrency refactor of the catalog have resolved the write concurrency issue exposed by the combination of batch writes during backfill and the on-disk aggregation plugin.
> Catalog & writer concurrency fixes

- cmd/marketstore/marketstore.go
- executor/wal.go
- executor/writtenIndexes.go
- executor/writtenIndexes_test.go
To avoid losing trigger writes on system exit, we will buffer them to a channel, and flush them before exiting.
> WrittenIndexes channel

- utils/io/serializer.go
Since all writes are converted to []byte before being serialized, simply appending the byte slice to the buffer rather than recursing should improve things.
> Optimize serialization for writes

- contrib/slait/slait.go
- contrib/slait/slait_test.go
- executor/cache.go
- executor/wal.go
- utils/io/columnseries.go
Batching was added to the Slait plugin because writes were too slow. Writes have since been optimized ~20x in https://github.com/alpacahq/marketstore/pull/52, so the batching was adding unnecessary complexity, and was preventing single writes from immediately being written to the DB. It has now been removed.
RequestFlush was also unnecessarily blocking in WriteCSM. The function will now not block if a flush is already queued in the TransactionGroupCache, since it is already going to flash as soon as possible.
On-disk data was also not being properly aligned to 64-bit. This has also been fixed.
> Slait plugin, alignment & WAL flush fixes

- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/ondiskagg/aggtrigger/util.go
- contrib/stream/streamtrigger/streamtrigger.go
- executor/wal.go
- executor/written.go
- executor/written_test.go
- plugins/trigger/trigger.go
- plugins/trigger/trigger_test.go
- utils/io/all_test.go
- utils/io/columnseries.go
`aggtrigger.so` was taking too long in combination with the polgyon plugin to aggregate 4 timeframes on the fly, hence this refactor and optimization. Now, instead of querying separately for each aggregate timeframe, only the base timeframe window is queried. The resulting column series is then cached, and as long as the next record is within that window, it will remain cached, and repeat queries will not be run. Once the trigger receives a record that is past the window, then the data will be re-queried, and the cache will be replaced.
This also required a change in how triggers work. Rather than only sending the index of records written, we are now sending the full index and payload as a `trigger.Record`. `streamtrigger.so` has been updated for this change.
> trigger refactor & aggtrigger optimization

- contrib/ondiskagg/aggtrigger/aggtrigger.go
Minor oversight - not handling empty query response when filtered by after-hour filter.
> after-hours aggtrigger nil checks

- Makefile
- contrib/binancefeeder/Makefile
- contrib/binancefeeder/README.md
- contrib/binancefeeder/binancefeeder.go
- contrib/binancefeeder/binancefeeder_test.go
Can be run by the following code in mkts.yml as such: 
```
bgworkers:
- module: binancefeeder.so
name: BinanceFetcher
config:
symbols:
- ETH
base_timeframe: "1Min"
query_start: "2018-01-01 00:00"
query_end: "2018-01-02 00:00"
```
Follows https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md and uses  https://github.com/adshao/go-binance gowrapper for binance. 
My main goal was to allow users to get cryptodata from binance for whatever currency, certain time range, and/or time frame. 
Also uses timeframe go library functionalities. Since the suffixes are different for the specific time intervals (ex: "1m" instead of "1Min"), I just mapped it to the correct one right before the API call.
> Add binance plugin

- contrib/binancefeeder/binancefeeder.go
Wrote function that parses millisecond timestamp that is received and converts it to Unix so that marketstore can correctly format it. 
Also, changed bgworker code so that it checks empty query strings
Also, adds findLastTimestamp functionality from gdaxfeeder
> Fix Time to Correct Unix Format and Check empty QueryStart and QueryEnd

- contrib/ondiskagg/aggtrigger/aggtrigger.go
head and tail were not being properly compared to with incoming bars, causing extra re-queries.
> aggtrigger caching fix

- contrib/binancefeeder/README.md
- contrib/binancefeeder/binancefeeder.go
- Fix query_end None behavior to collect data forever
- Fix GetAllSymbols to only get valid symbols
- If there is an APIError, go to previous timestamp. 
- Slow down to 1 minute per call after reaching queryEnd.
> Fixes query_end, GetAllSymbols, handling API Error behavior

- Gopkg.lock
- Gopkg.toml
- contrib/binancefeeder/README.md
- contrib/binancefeeder/binancefeeder.go
For the exchangeInfo, I realized all the Go wrappers out there handle the [/exchangeInfo](url) call totally incorrectly. I tried forking and implementing fixes with one of the libraries but for some reason the code stays the same as the original code when I import my forked Go version.
Thus, I just incorporated the `/exchangeInfo` call in the binancefeeder code without the wrapper. I also included additional checks in `getAllSymbols()` to ensure all the symbols can be called. 
I also fixed the time calls so that it doesn't call beyond the current timestsamp and made the pauses between each calls half the duration of the timeframe.
**Update**:
- time.sleep will slow down to time.Duration where timeEnd will be the time.Now() where the last candle in the previous timespan is fully formed. 
- …
> Fix overcalling and getAllSymbols() exchangeinfo call

- README.md
Current installation with docker assumes that the local environment should have some directory structures s.t. `/project`.
So, I changed readme as follows:
- Delete ``docker run -p 5993:5993 alpacamarkets/marketstore:v2.1.2``.
- Add assumptions for running ``docker run -v /tmp/mktsdb:/project/data/mktsdb -v /tmp/mkts.yml:/tmp/mkts.yml -p 5993:5993 alpacamarkets/marketstore:v2.3.8 marketstore -config /tmp/mkts.yml``.
> Fix the install doc with docker

- tests/integ/Makefile
- tests/integ/README.md
- tests/integ/dockerfiles/pyclient/Makefile
- tests/integ/requirements.txt
[tests/integ/Makefile]
- improved readability
- added `.PHONY` to each task
[tests/integ/dockerfiles/pyclient/Makefile]
- removed `-i -t` (interactive mode) from `docker run` to avoid `The input device is not a TTY` error that occurs when run from OSX
> refactor Makefiles of integration tests

- contrib/iex/backfill/backfill.go
Marketstore supports `1Min`, `5Min`, `15Min`, `1H`, `4H`, `1D` time frames, but iex plugin doesn't fill `4H` timeframe. This PR fixes this
> Fix missing time frame in backfill

- cmd/estimate/main.go
- cmd/main.go
- docs/design/file_format_design.txt
This PR adds a simple subcommand to estimate storage space. The math matches what's in `docs/design/file_format_design.txt`, so hopefully that's still accurate :)
Does not take into account any behavior of configured aggregator plugins, and has its defaults set for equities (matching the doc). Also assumes 1000 bytes per KB, which as far as I can tell, is the math that was used in the design doc.
> add cli command for estimating required storage space

- frontend/query.go
This PR adds support for querying all known symbols by using `*/<Timeframe>/<AttributeGroup>`
This does raise a question for me though: how is the list of known symbols actually determined? (how does it know data for the requested timeframe exists?) From my unfamiliar vantage point, it seems that if a symbol is listed in `mkts.yml` at all, then it appears to assume minutely data exists (and has been aggregated to higher timeframes)?
PS. This is the first Go code I've ever written, so if I'm doing something stupid, please do tell :)
> support querying for all known symbols with *

- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/ondiskagg/ondiskagg.go
- frontend/query.go
- planner/planner.go
- utils/timeframe.go
This PR implements timeframe aggregation on-the-fly.
The previous behavior was IMO a bit surprising, in that if you requested for example `2Min` it would appear to work, but actually it would return `1Min` data. Now, you will get `2Min` data (as long as `1Min` or `1Sec` data exists).
Tested (manually) with both `1Min` and `1D` as input data, as well as with persisted aggregate data (eg the aggtrigger is configured to store `5Min` and I request `10Min` data). Also fixed `CandleDuration.Truncate` so that it works correctly with weekly and yearly data, and monthly support was already correct. 
You can aggregate daily to yearly data, however at least with IEX, out-of-the-box it stores volume as `int32` which overflows for actively traded symbols. Support for persisting weekly/monthly/yearly …
> Queryable Timeframe Aggregation

- frontend/write.go
This PR is to enable the Destroy endpoint from pymarketstore.
See [this PR](https://github.com/alpacahq/pymarketstore/pull/32)
> Add message pack annotations to enable "Destroy" endpoint from pymarketstore

- contrib/binancefeeder/README.md
- contrib/binancefeeder/binancefeeder.go
- contrib/binancefeeder/binancefeeder_test.go
- contrib/gdaxfeeder/README.md
- contrib/gdaxfeeder/gdaxfeeder.go
- contrib/gdaxfeeder/gdaxfeeder_test.go
As per #94 this allows the binanceFeeder plugin to take any symbol available from the binance endpoint (https://api.binance.com/api/v1/exchangeInfo) I have updated the tests and have tested the new plugin locally.
You will need to update your database folders to reference the correct product ID. All output folders are prefixed with bianance_ this is for future crypto plugins to not clash if they share the same symbol. To retain your already downloaded data, rename your database folders like so:
```
BTC -> binance_BTC-USDT
ETH -> binance_ETH-USDT
```
example of the new mkts.yml configuration:
```yml
bgworkers:
- module: binancefeeder.so
name: BinanceFetcher
config:
symbols:
- ETH
base_timeframe: '1Min'
base_currencies:
- USDT
- BTC
query_start: '2018-01-01 00:00'
```
This will make 2 …
> binanceFeeder to take multiple base currencies

- contrib/bitmexfeeder/README.md
- contrib/bitmexfeeder/api/api.go
- contrib/bitmexfeeder/api/api_test.go
- contrib/bitmexfeeder/bitmexfeeder.go
- contrib/bitmexfeeder/bitmexfeeder_test.go
Keeping in line with my previous pull requests I have updated the bitmexFeeder to adapt to the new database folder structure. I have fixed a bug for only active symbols to be used by default and I have written tests for the BitMEX API plugin package I initially wrote.
You will need to update your database folders to reference the correct product ID. All output folders are prefixed with bitmex_ this is for future crypto plugins to not clash if they share the same symbol. To retain your already downloaded data, rename your database folders like so:
```
.XBT --> bitmex_XBTUSD
```
You can check the appropriate suffix symbols here: https://www.bitmex.com/api/v1/instrument/active
example of the new mkts.yml configuration:
```yml
bgworkers:
- module: bitmexfeeder.so
config:
query_start: …
```
> update bitmexFeeder to load correct symbols and save to bitmex_SYMBOL

- contrib/gdaxfeeder/README.md
- contrib/gdaxfeeder/gdaxfeeder.go
- contrib/gdaxfeeder/gdaxfeeder_test.go
As per #95 this allows the gdaxFeeder plugin to take any symbol available from the GDAX endpoint (https://api.pro.coinbase.com/products) I have updated the tests and have tested the new plugin locally.
You will need to update your database folders to reference the correct product ID. All output folders are prefixed with `gdax_` this is for future crypto plugins to not clash if they share the same symbol. To retain your already downloaded data, rename your database folders like so:
```
BTC -> gdax_BTC-USD
ETH -> gdax_ETH-USD
```
example of the new mkts.yml configuration:
```yml
bgworkers:
- module: gdaxfeeder.so
config:
query_start: '2018-01-01 00:00'
symbols:
- BTC-USD
- BTC-GBP
base_timeframe: '1D'
```
> gdaxFeeder to take any product ID

- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/ondiskagg/ondiskagg.go
- frontend/query.go
- planner/planner.go
- utils/timeframe.go
Reverts alpacahq/marketstore#205
This just failed in production by panic() when trying use a nil CS
I don't understand the code as written - I do see what look like some attractive immediate fixes, e.g. for the support of the 1Y timeframe - maybe we can break that out?
WRT queryable agg - maybe we can do a simpler thing here? Is this intended to allow for specification of arbitrary timeframes?
> Revert "Queryable Timeframe Aggregation"

- cmd/start/plugins.go
https://github.com/alpacahq/marketstore/blob/master/contrib/xignitefeeder/configs/config.go#L28
Some plugins have sensitive data such as a password or a token in their configs, and they shouldn't be output to the log.
We want to change the log level of the config dump log from `Info` to `Debug` so that we can hide the information by changing the log level.
> Loglevel update

- contrib/polygon/api/websocket.go
- planner/planner.go
In production we run marketstore with 70,000 symbols - this log message was causing the server to stop responding completely when our users were querying non-existent symbols
> Remove the recent change that logs the whole catalog

- utils/timeframe.go
The "1D" timeframe was replaced with "24H" in a recent PR, this reverts the API back to using "1D"
> Revert timeframe change

- contrib/iex/api/api.go
IEX returns error messages in the body, as opposed to returning valid JSON with an errors key. On `master` the code logs an error about parsing the JSON, eg:
`invalid character 'Y' looking for beginning of value`
Hiding the real error: 
`402 Payment Required: You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access`
This PR fixes it to show the real error in the logs
> log more helpful IEX cloud error messages

- contrib/iex/api/api.go
- contrib/iex/iex.go
This fix handles the IEX DELAYED_OTC error that can be encountered if you are not authorized for OTC tickers and you happen to request a ticker.  IEX has a bug in that if a symbol is both in OTC and non-OTC, the error condition can still occur.
As IEX does not report the offending symbol(s), this fix works by batching the symbol(s) into smaller batches if this error is encountered, recursively dividing the list until the affected symbol can be weeded out.  The symbol is also added to the blacklist and will not be queried for again.
> Handle DELAYED_OTC error IEX batch fetch can encoutner

- contrib/iex/iex.go
needed to complete intraday batches within minute timeframe (~10s now)
Also fixes the daily symbol refresh so that it updates the Symbols once a day (as well as Daily bar fetches if configured) and the batch work queue is refreshed from the new symbol list.
> Updated IEX polling to use multiple threads

- executor/writer.go
https://github.com/alpacahq/marketstore/compare/master...dakimura:fix/empty-csm-write?expand=1#diff-aa8668e426918b293917b241076b4820L302
`cs.GetTime()[0].Year()` can occur a panic if `cs.GetTime` is empty, and it was happening at a plugin that I am writing (XigniteFeeder Plugin)
This PR is to add a length check to avoid the panic!
> add length check to avoid panic

- contrib/polygon/api/api.go
This bug causes GetHistoricTrades function to limit total trades to 20,000 with a significant number of duplicate trades.
Cause: previously trades variable was declared outside the loop which was being reused for each iteration, hence the bug.
FIx: Declare trades variable inside the loop just before its use.
> Bug Fix: historic trades limited to 20k with duplicates

- contrib/polygon/README.md
Polygon's preferred method of subscribing to streaming services is no longer NATS.  Instead, users should use websockets.  The old readme did not detail how to use websockets, so I added `ws_servers` to the table and updated the example.
> Add websocket usage in Polygon plugin

- frontend/query.go
- utils/io/columnseries.go
With "columns" query parameter, marketstore server returns only the specified columns.
Please see https://github.com/alpacahq/pymarketstore/pull/35 also
> select columns feature

- contrib/bitmexfeeder/api/api.go
- contrib/bitmexfeeder/api/api_test.go
Let me fix the test that is failing on master branch.
- change "Errorf" to "Fatalf" so that the test stops there
- change the "startTime" request parameter to a valid one according to BitMex API spec
- print the error response to the log
> fix: bit mex API integration test - panic-able code

- contrib/polygon/backfill/backfill.go
- contrib/polygon/backfill/backfill_test.go
- contrib/polygon/backfill/backfiller/backfiller.go
- go.mod
Adds support to create backfill bars from Polygon tick data.
The exchanges to be included in the resulting bars can be specified, 
therefore polyfeed-like historical data can be constructed.
> ENH: Backfill from polygon tick data to bars

- README.md
Hi, I think homebrew is a proper way for macOS developers to manage software installation and extra plist for launchctl can be embraced via `brew services` for free.
a few issues still need to be addressed after then
* the [homebrew-marketstore](https://github.com/zjhmale/homebrew-marketstore) tap repository can be moved from my personal account to alpacahq account and I'm volunteered to be the maintainer
* the reason why I use `--HEAD` installation here is that the [latest release (v3.2.17)](https://github.com/alpacahq/marketstore/releases/tag/v3.2.17) of marketstore can not really work well with go@1.13.7 or newer, so I created the homebrew formula based on the master branch of the git repository instead of the `tar.gz` release file.
> docs(installation): add homebrew section for installation

- contrib/polygon/api/api.go
- contrib/polygon/backfill/backfiller/backfiller.go
Polygon recently deprecated API v1 in favor of API v2. This change moves the ListSymbols
function in backfeeder to use the new API.
> ENH: Move ListTickers (ListSymbols) to Polygon API v2 in backfeeder

- .circleci/config.yml
- go.mod
- WHAT
update circle CI version from 2.0 to 2.1.
- WHY
We can get many benefits by using the new features of Circle CI 2.1.
https://circleci.com/docs/ja/2.0/configuration-reference/#version-1
For just an example, I defined `executors` and reused the image definition in jobs.
> fix: update circleCI version from 2.0 to 2.1

- .circleci/config.yml
- Makefile
WHAT and WHY:
improve the build time by parallelizing unit-test and build processes.
> fix: parallelize build and unit test

- cmd/start/main.go
start marketstore ->
```
$ kill `pgrep marketstore`
```
The default signal sent is SIGTERM (c.f. [Wikipedia](https://en.wikipedia.org/wiki/Kill_(command)) )
->
```
{"level":"info","timestamp":"2020-03-29T12:39:58.496+0900","msg":"initiating graceful shutdown due to 'terminated' request"}
```
> fix: catch sigterm signal

- executor/wal.go
- go.mod
This pull request makes the response time of `write` operation 2 times faster by reducing the number of `fp.Sync()` calls in WAL write process.
The most time-consuming part of a write operation is `fp.Sync()`.
In a write operation, marketstore calls `fp.Sync()` 4 times for the following steps:
[WAL write]
1. [WAL write] write a Transaction Info message with "PREPARING" status to WAL file
1. [WAL write] write a Transaction Group Data message  to WAL file
1. [WAL write] write a Transaction Info message with "COMMIT COMPLETE" status to WAL file
1. [Data write] write the actual data to primary store
One `fp.Sync()` call takes 5-6msec, so it is currently taking 20-24msec for 1 write and it's 80~90% time for the operation.
Of course, we need to `Sync` after WAL write, but we don't need to …
> reduce the number of fp.Sync() calls for a WAL write from 3 to 1

- .circleci/config.yml
- Dockerfile
- Makefile
- tests/integ/Makefile
- tests/integ/bin/runtests.sh
- tests/integ/dockerfiles/pyclient/Makefile
[WHAT]
- make the build of marketstore and its plugins parallel
- make the CSV import test and other integration tests parallel
- don't include plugins in the docker container for the integration tests
- remove unused test data
- use Circle CI variables for filters
[WHY]
- to make CI fast
> CI speed improvement

- contrib/polygon/handlers/handlers.go
* Fix for the following error:
```{"level":"error","timestamp":"2020-04-24T13:34:04.109Z","msg":"[polygon] csm write failure for key: [BTU/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (unable to match data columns ([{Epoch INT64} {Open FLOAT32} {High FLOAT32} {Low FLOAT32} {Close FLOAT32} {Volume INT32}]) to bucket columns ([{Epoch INT64} {Open FLOAT32} {High FLOAT32} {Low FLOAT32} {Close FLOAT32} {Volume INT32} {TickCnt INT32}]))"}```
> Fix polygon database schema difference

- planner/planner.go
fix for https://github.com/AlpacaDB/marketstore-tests/issues/28
> fix: avoid panic when the root category is empty

- cmd/start/main.go
- tests/integ/dockerfiles/pyclient/requirements.txt
WHAT:
always trigger grpcServer.GracefulStop when interrupted
WHY:
when I stop marketstore by Ctrl+C , sometimes grpc port is not closed and I can't restart it for "address already used" error
> fix: trigger grpcServer.GracefulStop when interrupted

- README.md
Document how to bind-mount in a `mkts.yml` config for quick testing of
the image included plugins. Fix the python blocks so they highlight
correctly. Mention that you have to build the `cmd` package before using
the `connect` command.
> Document how to bind-mount a mkt.yml

- Dockerfile
The current marketstore version does not contain ca-certificates package
pre-installed, thus the backfill process fails:
```
{"level":"warn","timestamp":"2020-06-07T17:57:59.296Z","msg":"[polygon] failed to backfill bars for NUGY @ 2020-01-31 00:00:00 +0000 UTC (Get \"https://api.polygon.io/v2/ticks/stocks/trades/NUGY/2020-01-31?apiKey=xyz&limit=50000\": x509: certificate signed by unknown authority)"}
```
> Fix: Add ca-certificates to docker image

- contrib/polygon/handlers/handlers.go
- contrib/polygon/polygon.go
- tests/integ/tests/test_grpc.py
Polygon SIP and Polygon Polyfeed database schemas are different. SIP does not contain TickCnt for bars while Polyfeed does. This change allows us to use the same image for both.
Relates to: #313 Fix polygon database schema difference
> Make polygon db schema configurable

- Makefile
The freshly built image does not output version information:
```sh
root@ae18fa7238c1:/# marketstore --version
{"level":"info","timestamp":"2020-06-12T10:04:10.050Z","msg":"Running single threaded"}
version:
commit hash:
utc build time:
```
With this fix:
```sh
root@eafef63756c8:/# marketstore --version
{"level":"info","timestamp":"2020-06-12T10:05:00.162Z","msg":"Running single threaded"}
version: latest
commit hash: ba8dd4ea082e78ee571c54d9a5bf9e70d3b29fbd
utc build time: 2020-06-12-10-00-06
```
> fix: build and version information for --version parameter

- contrib/polygon/api/api.go
- contrib/polygon/api/schema.go
- contrib/polygon/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- executor/rewritebuffer.go
- executor/sort.go
- tests/integ/tests/test_grpc.py
* changed historical aggregates endpoint from `v1/historic/agg` to `v2/aggs/ticker`
* changed how command line `-from` and `-to` date parameters are handled: **from** is included and **to** is not
* removed `import "C"` lines to be able to cross-compile `backfiller` binary
> fix: follow polygon REST api change on backfilling bars

- frontend/query.go
- frontend/query_test.go
- tests/integ/dockerfiles/pyclient/requirements.txt
WHAT
- `pymkts_cli.list_symbols(fmt=ListSymbolsFormat.TBK)` returns TBK names (e.g.  ['TSLA/1Min/OHLCV' , 'AAPL/1Min/TICK'] )
- change the default response of list_symbols API from `None` to `[]` because it will be easier to handle (e.g. `len(cli.list_symbols())` returns an error if `None` is returned)
> feat: list TBK names by json-rpc client

- contrib/iex/backfill/backfill.go
- executor/all_test.go
- executor/errors.go
- executor/instance.go
- executor/messages.go
- executor/wal.go
- executor/wal/errors.go
- executor/wal/file.go
- remove InstanceID(= a kind of process ID) from Instance Config and embed it in the WAL file
- InstanceMetaData is a singleton and it makes unit-test difficult
- WAL is the only user of the Instance ID
> refactor: remove Instance ID from Instance Config

- go.mod
- go.sum
- utils/io/byteconversions.go
- utils/io/datashape.go
- utils/io/datashape_test.go
- Add functionality to Serialize/Deserialize DataShape.
- In order to implement replication feature using WAL binary, DataShape information for each bucket should be added to WAL, because replica instances need to create buckets from WAL but it's impossible without the DataShape information(=column names and their data types)
> add: serialize/deserialize data shape

- contrib/candler/tickcandler/all_test.go
- executor/all_test.go
- executor/cache.go
- executor/wal.go
- executor/writer.go
- sqlparser/insertintostatement.go
- utils/io/datashape.go
- utils/io/datashape_test.go
- include DataShape information in WAL message
- to implement replication using WAL, DataShape information is necessary because replica instances need to create bucket files from WAL.
> add: include DataShape in WAL message

- executor/cache.go
- executor/wal.go
- executor/wal/oib.go
- executor/wal/wt.go
- executor/writer.go
- executor/written_test.go
move OffsetIndexBuffer and WTSet structs to wal package
to make wal.go simpler for visibility
> refactor: move OffsetIndexBuffer and WTSet to another file

- contrib/candler/candler.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- executor/scanner.go
- planner/planner.go
- plugins/trigger/trigger.go
- plugins/trigger/trigger_test.go
- utils/io/columnseries.go
- utils/io/datatypes.go
- utils/io/rowseries.go
I found that `CandleAttributes` type is defined and set to many structs but never be used in marketstore...
I don't know if there are any plans to use this, but let me remove this for now...
> chore: remove CandleAttribute from row

- executor/writer.go
This PR makes it so that clients making write requests do not need to know what types `marketstore` uses to store its on-disk data
> coerce types on write for column series data to match on-disk types

- executor/ticks_test.go
- tests/integ/tests/test_1day_timeframe.py
- utils/io/all_test.go
- utils/io/timeindex.go
- utils/io/timeindex_test.go
- update the code to calculate index from time, and time from index so that the index starts from 1 for 1day timeframe.
- If we allow index=0 as a valid record, it causes an issue when we query data stored on Jan.1st 00:00:00 (-> index=0. the epoch column binary is filled with 0) because marketstore can't distinguish them with empty data
> fix: index starts from 1 for 1day timeframe

- cmd/connect/session/client.go
- cmd/connect/session/load.go
- cmd/connect/session/show.go
remove escapes by using back quotes because a string encoded in back quotes is a raw literal string and doesn’t honor any kind of escaping in Golang.
small refactor
> fix: remove escapes by using back quotes

- cmd/connect/session/create.go
- add an error handling for \create command
- A panic happens when not enough arguments are passed to \create command
> fix: suppress the panic of create command

- cmd/connect/loader/utils.go
- cmd/connect/session/load.go
- print log when a CSV file is imported using the local mode
- Without the log, it's confusing that the data is not updated until restart marketstore.
> info log when CSV is imported using local mode

- cmd/connect/main.go
- cmd/start/main.go
- use config object instead of utils.InstanceConfig
- In the future, we want to stop using InstanceConfig because it's a singleton object and hard to write unit tests
> chore: small refactor to prepare for Dependency Injection

- cmd/start/main.go
- contrib/polygon/backfill/backfiller/backfiller.go
- utils/config.go
- stop using `executor.ThisInstance.RootDir/Triggers` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): rootDir and TriggerSettings

- cmd/connect/session/client.go
- cmd/start/main.go
- contrib/alpaca/handlers/handlers_test.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/tickcandler/all_test.go
- contrib/ice/cmd/reorg/import.go
- contrib/ice/cmd/reorg/show.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/polygon/handlers/handlers_test.go
- executor/all_test.go
- executor/instance.go
- frontend/server_test.go
- frontend/stream/stream_test.go
- sqlparser/all_test.go
- stop using `executor.ThisInstance.WALRotateInterval` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): executor.ThisInstance.WALRotateInterval

- cmd/start/main.go
- cmd/start/plugins.go
- pass MktsConfig to marketstore plugins
- to stop using the singleton config `utils.InstanceConfig` in the near future
> refactor: pass config to plugins

- contrib/binancefeeder/binancefeeder.go
- contrib/bitmexfeeder/bitmexfeeder.go
- contrib/gdaxfeeder/gdaxfeeder.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/polygon/polygon.go
- contrib/stream/streamtrigger/streamtrigger.go
- pass MktsConfig.DisableVariableCompression config to plugins
- tried to stop using the singleton config `utils.InstanceConfig.DisableVariableCompression` but currently there is no way to inject the config without using the singleton config
> bugfix: pass MktsConfig to plugins

- executor/all_test.go
- executor/instance.go
- executor/wal.go
- stop using `utils.InstanceConfig.WalBypass` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): utils.InstanceConfig.WalBypass

- cmd/start/main.go
- frontend/utilities.go
- frontend/utilities_test.go
- stop using `utils.InstanceConfig.startTime` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): utils.InstanceConfig.startTime

- cmd/connect/session/create.go
- cmd/connect/session/load.go
- cmd/start/main.go
- contrib/candler/tickcandler/all_test.go
- contrib/iex/backfill/backfill.go
- executor/instance.go
- frontend/grpc.go
- frontend/query_test.go
- frontend/server.go
- frontend/server_test.go
- frontend/write.go
- frontend/write_test.go
- stop using `executor.ThisInstance.RootDir` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): executor.ThisInstance.RootDir

- cmd/start/main.go
- contrib/candler/tickcandler/all_test.go
- contrib/iex/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- executor/all_test.go
- executor/instance.go
- executor/wal.go
- frontend/server_test.go
- stop using `executor.ThisInstance.ShutdownPending` and `executor.ThisInstance.WALBypass` and pass it as a function argument or struct parameter for each module
> refactor(stop using singleton config): executor.ThisInstance.ShutdownPending&WALBypass 

- cmd/connect/session/client.go
- cmd/connect/session/show.go
- cmd/connect/session/trim.go
- cmd/start/main.go
- contrib/iex/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- executor/all_test.go
- executor/instance.go
- executor/wal.go
- stop using `executor.ThisInstance.CatalogDir` and `executor.ThisInstance.WALWg` and pass it as a function argument or struct parameter for each module
> refactor: stop using singleton config. catalogDir & WalWG

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- contrib/alpaca/handlers/handlers_test.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/tickcandler/all_test.go
- contrib/ice/cmd/reorg/show.go
- contrib/iex/backfill/backfill.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/polygon/handlers/handlers_test.go
- executor/all_test.go
- executor/instance.go
- frontend/server_test.go
- sqlparser/all_test.go
- uda/adjust/adjust_test.go
- uda/adjust/caloader_test.go
to fix the panic issue when shutting down marketstore by Ctrl+C
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x407e8e6]
goroutine 38 [running]:
sync.(*WaitGroup).state(...)
/usr/local/Cellar/go/1.15.2/libexec/src/sync/waitgroup.go:33
sync.(*WaitGroup).Wait(0x0)
/usr/local/Cellar/go/1.15.2/libexec/src/sync/waitgroup.go:104 +0x26
github.com/alpacahq/marketstore/v4/cmd/start.shutdown(0xc0002312f0, 0x0)
/Users/dakimura/projects/go/src/github.com/alpacahq/marketstore/cmd/start/main.go:244 +0x38
github.com/alpacahq/marketstore/v4/cmd/start.executeStart.func2(0xc00004e0c0, 0xc00016c000, 0xc000208470, 0xc0002581a0, 0x552f2c0, 0xc0002312f0, 0xc00021c780) …
```
> fix: remove walWG from instance config

- cmd/start/main.go
- go.mod
- go.sum
- replication/receiver.go
- replication/receiver_test.go
- replication/retry.go
- replication/retry_test.go
- utils/config.go
- add a retry feature for the replication feature.
When replication fails, it retries after an interval that can be configured by mkts.yml.
- sometimes a replica instance loses the connection to the master instance.
> feat: retry logic for replication feature

- contrib/candler/tickcandler/all_test.go
- executor/all_test.go
- executor/writer.go
- sqlparser/insertintostatement.go
- utils/config.go
- stop using `executor.ThisInstance.WALFile` from `NewWriter` function
- singleton instances make unit test difficult
> fix: a step to stop using "ThisInstance" singleton instance

- tests/integ/dockerfiles/pyclient/requirements.txt
- update pymarketstore version for integration test
- pymarketstore updated its depending msgpack version, so it's preferrable to test marketstore by the latest pymarketstore version
> fix: update pymkts version for integtest

- sqlparser/all_test.go
- sqlparser/executablestatement.go
- sqlparser/selectrelation.go
- support Nanosec precision predicate for SELECT SQL query.
```
if __name__ == "__main__":
cli = pymkts.Client()
tbk = "TEST/1Sec/OHLCV"
dtype = [('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Nanoseconds', 'i4')]
cli.destroy(tbk)
data = [
np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10 ** 9, 1, 2, 100000000)], dtype=dtype),
np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10 ** 9, 3, 4, 200000000)], dtype=dtype),
np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10 ** 9, 5, 6, 300000000)], dtype=dtype),
np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10 ** 9, 7, 8, 400000000)], dtype=dtype)
]
for record in data:
cli.write(record, tbk, isvariablelength=True)
sql = "SELECT * FROM `TEST/1Sec/OHLCV` WHERE Epoch BETWEEN '2019-01-01-00:00:00.15' AND …
```
> feat(sql): nanosec support

- cmd/connect/session/local_api_client.go
- frontend/grpc.go
- frontend/query.go
- sqlparser/all_test.go
- sqlparser/datatypes.go
- sqlparser/executablestatement.go
- sqlparser/interpreter.go
Only `ast.Mtree`(=query tree) is necessary, we can remove AstBuilder struct
> refactor: remove unused AstBuilder struct

- executor/writer.go
- sqlparser/insertintostatement.go
- utils/io/metadata.go
- Make all modules use WriteCSM instead of writer.WriteRecords.
- improve refactorability
> refactor: use WriteCSM instead of writer.WriteRecords

- cmd/tool/wal/main.go
- executor/instance.go
- executor/wal.go
- executor/wal/command.go
- executor/writer.go
- utils/io/metadata.go
- remove `RootPath string` parameter from WAL struct
- The rootDir can be obtained from `filePtr *os.File`.
- The physical directory where the WALfile resides should be hidden from other services in the future, for better portability/testability/abstraction.
> refactor: remove RootPath from WAL struct

- executor/all_test.go
- executor/wal_test.go
- separate some test functions related to WAL from all_test.go and use testing.T
- for better readability
- to make each test function more independent
> refactor(wal): separate test files and use testing.T

- catalog/catalog.go
- catalog/catalog_test.go
- contrib/alpaca/handlers/handlers_test.go
- frontend/query.go
- frontend/query_test.go
- frontend/server_test.go
- frontend/write_test.go
- a part of refactor to use testing.T instead of TestSuite
- to make each test more independent (and parallelize in the future)
> refactor: use testing.T instead of TestSuite

- contrib/candler/tickcandler/all_test.go
- executor/buffile/buffile.go
- executor/buffile/buffile_test.go
- frontend/stream/stream_test.go
- frontend/utilities_test.go
- planner/planner_test.go
- plugins/load_test.go
- plugins/trigger/trigger_test.go
- uda/adjust/adjust_test.go
- utils/io/numpy_test.go
- a part of refactor to use testing.T instead of TestSuite
- to make each test more independent (and parallelize in the future)
> refactor(test): use testing.T instead of TestSuite

- contrib/candler/tickcandler/all_test.go
- executor/all_test.go
- executor/instance.go
- executor/wal.go
- executor/wal_test.go
- executor/writer.go
- go.mod
- go.sum
- refactor: wrap TransactionPipe object in WAL
- WAL is the only user of Transaction Pipe, so some code can be simplified by making TransactionPipe and WAL as a set (e.g. Transaction Pipe can be removed from the singleton `ThisInstance` config)
> refactor: wrap TransactionPipe in WAL

- contrib/iex/backfill/backfill.go
- executor/instance.go
- refactor: remove `rootDir` from the `ThisInstance` singleton config
- to improve testability
> refactor: remove rootDir from the singleton config

- contrib/candler/tickcandler/all_test.go
- executor/all_test.go
- executor/wal_test.go
- executor/writer.go
- remove TimeBucketInfo from Writer struct params and add it as an argument of writer.WriteRecords function
- refactor: We want to share a writer for multiple write requests in the near future
> refactor: remove TimeBucketInfo from writer struct params

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- executor/writer.go
- frontend/query_test.go
- frontend/server.go
- frontend/server_test.go
- frontend/write.go
- frontend/write_test.go
- add WriteCSM function to Writer struct and use it instead of static WriteCSM function
- refactor to improve testability
> refactor: use non-static WriteCSM function

- sqlparser/all_test.go
- sqlparser/registry.go
- remove aggregator function names in camelCase
- refactor. the function name is already being compared after `ToLower` function, so only function names in lower cases are necessary
https://github.com/alpacahq/marketstore/blob/5b3671d40bf7820a7b982cef1899c8e3a24ba0a6/frontend/query.go#L356
> refactor: use only lower case for agg function name

- contrib/candler/candlecandler/all_test.go
- contrib/candler/candlecandler/candlecandler.go
- contrib/candler/tickcandler/all_test.go
- contrib/candler/tickcandler/tickcandler.go
- frontend/query.go
- sqlparser/all_test.go
- sqlparser/selectrelation.go
- uda/adjust/adjust.go
- uda/adjust/adjust_test.go
- uda/avg/avg.go
- uda/count/count.go
- uda/datatypes.go
- uda/gap/gap.go
- uda/max/max.go
- uda/min/min.go
include TimeBucketKey name in Accum function arguments
In order to improve testability of Aggregator functions, AggregatorFunctions need to be a static function (not a stateful function). By removing "SetTimeBucketKey" function from aggfunc and include TimeBucketKey in the arguments, aggfunc becomes more static.
> refactor: include tbk to arguments of Accum function

- .codecov.yml
- exclude integration test files for the calculation of test coverage.
- without the rule, the more integration tests are added the worse test coverage gets
> fix: ignore test files for coverage calculation

- contrib/candler/candlecandler/all_test.go
- contrib/candler/candlecandler/candlecandler.go
- contrib/candler/candler.go
- contrib/candler/tickcandler/all_test.go
- contrib/candler/tickcandler/tickcandler.go
- frontend/query.go
- sqlparser/all_test.go
- sqlparser/selectrelation.go
- uda/adjust/adjust.go
- uda/adjust/adjust_test.go
- uda/avg/avg.go
- uda/count/count.go
- uda/datatypes.go
- uda/gap/gap.go
- uda/max/max.go
- uda/min/min.go
remove `Output()` function from AggFunc interface
simplify AggFunc interface and make it static to improve testability
> fix: remove Output function from AggFunc

- tests/integ/tests/test_ticks.py
- tests/integ/tests/utils.py
- use `view` for casting datetime to int
to address the following error:
```
FutureWarning: casting datetime64[ns, UTC] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
```
> fix(integtest): change astype to view

- cmd/start/main.go
- metrics/du.go
- metrics/du_test.go
- metrics/metrics.go
- Add Prometheus Metrics to monitor the disk usage consumed by the marketstore data directory.
```
$ curl -s http://localhost:5993/metrics | grep alpaca_marketstore_total_disk_usage_bytes
alpaca_marketstore_total_disk_usage_bytes 3.759292416e+09
```
- As the more data the marketstore writes, errors can occur due to the out of disk space, so we want to add metrics that can be monitored.
> add: prometheus metric to monitor the disk usage of the data directory

- executor/wal.go
- don't return an error in write transaction but continue the process
- One of the factors that may cause a write transaction to fail is when data cannot be written to a file due to unexpected deletion of the data file from the OS. In such a case, rather than giving up other write requests in the same transaction set due to the failure of the corresponding data, it is considered to be closer to the expected result to continue to attempt to process those other write requests.
Currently, marketstore's DELETE API is implemented to simply delete data files from the OS without going through WAL, which may well lead to such an event.
> fix(wal): continue transaction if it's partially failed

- cmd/connect/session/local_api_client.go
- cmd/start/main.go
- contrib/alpaca/handlers/handlers_test.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/tickcandler/all_test.go
- contrib/ice/cmd/reorg/import.go
- contrib/ice/cmd/reorg/show.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/backfill/backfiller/backfiller.go
- contrib/polygon/handlers/handlers_test.go
- executor/all_test.go
- executor/instance.go
- executor/wal.go
- frontend/query_test.go
- frontend/stream/stream_test.go
- sqlparser/all_test.go
- uda/adjust/adjust_test.go
- utils/config.go
same as title
`log.Fatal` not only prints a log, but also terminates the marketstore process.
Therefore, using `log.fatal` outside of the main function may cause issues due to unexpected process termination.
> refactor(log): avoid using log.fatal and do error handlings

- contrib/bitmexfeeder/bitmexfeeder.go
- contrib/bitmexfeeder/bitmexfeeder_test.go
- use mock API response for BitMex feeder unit test
- API mock has been used since before this refactor, but it was not entirely used for the test
- to stabilize the unit test by using the mock.
> refactor(bitmex): mock API response

- .circleci/config.yml
- Dockerfile
update the go build version from 1.17.0 to 1.17.1
The go minor release includes a security fix according to the new security policy and a panic/fatal error.
https://groups.google.com/g/golang-announce/c/dx9d7IOseHw?pli=1
> build: update go version to 1.17.1

- executor/instance.go
- executor/wal.go
- executor/wal_test.go
- executor/walreplay.go
- move wal_replay logics to `walreplay.go`
- add error handlings to wal logics
The wal package does not do much error handling and marketstore is often eventually killed by log.Fatal()/panic() caused by the package.
This is one of the PRs to continuously refactor for proper error handling, such as showing the cause of err in the log and recovering wal when possible.
> refactor(wal): add error handlings

- cmd/connect/session/trim.go
- executor/all_test.go
- executor/scanner.go
- executor/wal.go
- executor/wal/file.go
- executor/walreplay.go
- utils/io/metadata.go
- utils/test/setup.go
- replace os.SEEK_* with io.Seek* as they are deprecated
- improve readability by using early return
- refactor for readability
> refactor(wal): readability improvement by early return

- contrib/xignitefeeder/feed/interval.go
- executor/errors.go
- executor/instance.go
- executor/wal.go
- executor/wal/errors.go
- executor/wal/find.go
- executor/wal/move.go
- executor/wal_test.go
- executor/walclean.go
- executor/walreplay.go
- feature to move wal file to a temporary file when WAL replay failed, and continue marketstore startup process
- change some unimportant errors' loglevel from ERROR to WARN
- add error handlings
- separate some logics to independent small structs
- When marketstore starts up, it replays old WAL files if any, but if the WAL replay fails, the marketstore is forced to shut down (without this PR). However, the only thing the operator can do manually after that is to delete the WAL file and restart the marketstore.
This PR is to reduce the operational load by automatically saving the WAL file to a temporary file and continuing the marketstore startup process when the replay fails.
- add more information in case of errors
- refactor for better code readability
> feat(wal): move wal file to a temporary file when WAL replay failed

- catalog/catalog.go
- catalog/catalog_test.go
- catalog/errors.go
- executor/all_test.go
- executor/instance.go
- when `category_name` file is not found in a directory for a symbol, marketstore ignores the directory.
- When a data directory is deleted manually or by Delete API, it's possible that only files (`category_name` and `****.bin`) are deleted and some directories (e.g. `/AAPL/1Sec/` directory in `AAPL/1Sec/TICK` data directory) remains. In that case, marketstore shows "category_name not found" error and hangs. This PR will ignore such partially deleted directories and continue other processes.
> refactor(category): ignore partially deleted data dir

- cmd/tool/integrity/main.go
- contrib/calendar/calendar.go
- contrib/ice/cmd/reorg/import.go
- contrib/ice/reorg/import.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/polygon/backfill/backfiller/backfiller.go
- executor/instance.go
- utils/config.go
- replace `log.Fatal` to `log.Error` + appropriate error handling
- `log.Fatal` shutdowns the marketstore process, which causes unexpected operation issues
> refactor(log): avoid using fatal log

- executor/scanner.go
- Fixed a bug in the loop that reads a data file when it is queried.
If `numRead==bytesToRead`, read can be finished.
- This bug causes high CPU usage issues.
> fix(query): off-by-one bug in read size check after read

- cmd/connect/main.go
- cmd/connect/session/client.go
- cmd/connect/session/local_api_client.go
- cmd/connect/session/mock/client.go
- cmd/connect/session/remote_api_client.go
- cmd/connect/session/remote_api_client_test.go
- planner/planner.go
- fix a bug that CSV import through a remote marketstore connection using `marketstore connect --url {hostname}:{port}` always fails.
- bug fix.
> bugfix(cli): CSV import via remote marketstore connection

- cmd/tool/integrity/main.go
- contrib/ice/reorg/import.go
- contrib/ice/reorg/record.go
- contrib/iex/backfill/backfill.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/api/api.go
- contrib/polygon/backfill/backfiller/backfiller.go
- executor/wal.go
- models/bar.go
- models/bar_test.go
- utils/config.go
- utils/test/setup.go
- replace `log.Fatal` to `log.Error` + appropriate error handling
- `log.Fatal` shutdowns the marketstore process, which causes unexpected operation issues
> refactor(error): remove log.fatal and add error handlings

- cmd/connect/session/create.go
- cmd/connect/session/create_test.go
- cmd/connect/session/load.go
- contrib/xignitefeeder/writer/bar_writer_test.go
- contrib/xignitefeeder/writer/quotes_range_writer_test.go
- contrib/xignitefeeder/writer/quotes_writer_test.go
- replication/replay_test.go
- utils/io/keytypes.go
- utils/io/keytypes_test.go
- unexport the Key parameter of TimeBucketKey
- some implementations were assuming TimeBucketKey.Key parameter as "AAPL/1Min/OHLC" format, some were "AAPL/1Min/OHLC:Symbol/Timeframe/AttributeGroup" format. To avoid the confusion, unexport the parameter and ask the users of this struct to explicitly use `tbk.GetItemKey()` function to get "AAPL/1Min/OHLC" part.
> refactor(tbk): unexport Key parameter of TimeBucketKey struct.

- cmd/connect/session/show.go
- validate itemKey argument of `\show` command by before passing it to `io.NewTimeBucketKey()` function
- `\show` command causes a panic if it gets a key that is not in `{Aymbol}/{Timeframe}/{AttributeGroup}` format
> bugfix(show): possible panic in show command

- cmd/connect/session/client.go
- `\show` command prints `(%d rows * %d columns)` at the bottom
e.g.
```
\show MTB_quote_iex/1Sec/Tick 1970-01-01
(...skipping...)
2021-11-26 17:56:36 +0000 UTC      153.79      153.87   245917352  
2021-11-26 17:56:36 +0000 UTC      153.79      153.87   257680785  
2021-11-26 17:57:49 +0000 UTC      154.23      154.33   497324555  
2021-11-26 17:58:00 +0000 UTC      154.21      154.35   198279300  
2021-11-26 17:59:58 +0000 UTC      154.01      154.18   461854806  
2021-11-26 17:59:58 +0000 UTC      154.01      154.18   931088122  
=============================  ==========  ==========  ==========  
(2850 rows * 4 columns)
```
- inspired by MySQL and other SQL CLIs. helpful for debugging.
> feat(show): print the number of rows and columns at show cmd

- contrib/xignitefeeder/api/client.go
- contrib/xignitefeeder/api/model.go
- contrib/xignitefeeder/configs/config.go
- contrib/xignitefeeder/internal/mocks.go
- contrib/xignitefeeder/symbols/manager.go
- contrib/xignitefeeder/test/integ/tests/text.py
- contrib/xignitefeeder/writer/quotes_writer.go
- remove unnecessary comment like `//-------`
- change level of the log shown when ListIndexSymbols API fails from WARN to ERROR
- add Info log before calling GetRealTimeQuotes API
- refactor
> refactor(xignite): remove unnecessary comments and files

- catalog/catalog.go
- contrib/ice/ftp/client_mock.go
- contrib/ice/ftp/downloader.go
- contrib/ice/reorg/import.go
- executor/instance.go
- executor/wal/find.go
As of go1.16, `io/ioutil` is deprecated.
> fix: deprecate ioutil.ReadDir

- catalog/catalog_test.go
- contrib/alpaca/handlers/handlers_test.go
- contrib/candler/candlecandler/all_test.go
- contrib/candler/tickcandler/all_test.go
- contrib/ondiskagg/aggtrigger/aggtrigger_test.go
- contrib/polygon/handlers/handlers_test.go
- executor/all_test.go
- executor/buffile/buffile_test.go
- executor/wal_test.go
- frontend/query_test.go
- frontend/server_test.go
- frontend/stream/stream_test.go
- frontend/write_test.go
- metrics/du_test.go
- planner/planner_test.go
- plugins/load_test.go
- sqlparser/all_test.go
- uda/adjust/adjust_test.go
- uda/adjust/caloader_test.go
- utils/io/all_test.go
A small testing enhancement here.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
Signed-off-by: Eng Zer Jun <engzerjun@gmail.com>
> test: use `T.TempDir` to create temporary test directory

- contrib/alpacabkfeeder/writer/snapshot_writer.go
- contrib/alpacabkfeeder/writer/snapshot_writer_test.go
- Alpaca Broker Feeder plugin: add `Trade`, `DailyBar`, `MinuteBar`, and `PreviousBar` data to `{symbol}/1Sec/TICK` buckets
- to store all the data in the response of `GetSnapshot` Alpaca API endpoint
> feat(alpacabkfeeder): add columns to store

- contrib/alpacabkfeeder/configs/config_test.go
- contrib/alpacabkfeeder/configs/envconfig.go
- contrib/alpacabkfeeder/feed/backfill.go
- `ALPACA_BROKER_FEEDER_STOCKS_JSON_URL` overrides the config in mkts.yml
- to use different URLs depending on env
> fix(alpacabkfeeder): override stocks_json URL by env var

- frontend/grpc.go
- frontend/query.go
- tests/integ/dockerfiles/pyclient/requirements.txt
- tests/integ/tests/test_query_multi_symbols.py
- utils/io/columnseries.go
- return multiple symbols data if common columns are specified on a query.
- some OHLCV symbols have columns other than Open/High/Low/Close/Volume, but sometimes we want to query just OHLCV columns for those different symbols in one query.
> feat(query): query multiple symbols of different data format

- contrib/xignitefeeder/configs/config.go
- contrib/xignitefeeder/configs/config_test.go
- add validation for the Xignite Token
- to avoid accidental DOS to Xignite API
> fix(xignitefeeder): validate API token length

- contrib/candler/candler.go
- contrib/ondiskagg/aggtrigger/aggtrigger.go
- contrib/stream/streamtrigger/streamtrigger.go
- frontend/query.go
- uda/adjust/caloader.go
- uda/gap/gap.go
- utils/timeframe.go
- utils/timeframe_test.go
- fix a possible panic that occurs when invalid timeframe string is specified in the query/write request
(e.g. when queried `FOO/BAR/1Min/OHLCV` , marketstore was panicking)
- bugfix
> fix(timeframe): handle an error due to an invalid timeframe string

- cmd/start/main.go
- contrib/polygon/backfill/backfiller/backfiller.go
- planner/planner.go
- utils/config.go
- add `NewDefaultConfig` function
- minor refactors
- it is necessary to add a function to initialize the config without using the singleton instance (= `utils.InstanceConfig` ) for Dependency Injection
> refactor: add default config

- uda/adjust/adjust.go
- uda/adjust/adjust_test.go
- uda/adjust/caloader.go
- uda/adjust/caloader_test.go
- uda/uda.go
- utils/config.go
rename the package name of ***_test.go files under /adjust to `adjust_test`
- refactor.
- It can cause an import cycle at later PRs
> refactor(adjust): rename test package to adjust_test

- utils/io/coercecolumn_test.go
- utils/io/datashape_test.go
- utils/io/datatypes.go
- utils/io/enumelementtype_string.go
- utils/io/rowseries.go
remove `io.EPOCH` from Element Type enum
every bucket has `epoch` column but its element type is `INT64`. `EPOCH` should not be an element type.
> refactor: remove io.Epoch element type

- contrib/alpacabkfeeder/README.md
- contrib/alpacabkfeeder/alpacav2.go
- contrib/alpacabkfeeder/configs/config.go
- contrib/alpacabkfeeder/feed/time_checker.go
- contrib/alpacabkfeeder/feed/time_checker_test.go
- contrib/alpacabkfeeder/writer/snapshot_writer.go
- contrib/alpacabkfeeder/writer/snapshot_writer_test.go
- add `extended_hours` config in the AlpacaBrokerAPIFeeder plugin.
- when `extended_hours: false`, TICK data during the off-hours (= time < openTime and time > closeTime) are dropped and not stored in DB, even when `off_hours_schedule` is set.
- see `contrib/alpacabkfeeder/README.md` for the details.
> feat(alpacabkfeeder): extended_hours config

- go.mod
- remove ununsed replace directive from go.mod
- it causes an error when `go install`
> fix: remove replace from go.mod

- README.ja.md
- README.md
- contrib/alpacabkfeeder/feed/time_checker.go
- check isOpenTime before isOpenDate and isOpenWeekDay check
- remove debug logging on the time check
- the isOpen function is called more frequently than before (~100/sec?), so the logging can be too much load
- isOpenTime returns false more frequently than isOpenWeekDay and isOpenDate, it could return early if it's checked first
> fix(alpacabkfeeder): tweak on isOpenTime check

- go.mod
- go.sum
- utils/io/datatypes.go
- utils/io/enumelementtype_string.go
- revert `EPOCH` datatype
- because the enum value is used in header files. Once a data type is added, we must not delete it to keep the compatibility of the file format.
> bugfix: revert epoch type

- contrib/alpacabkfeeder/configs/config.go
- bugfix: add json parse for `extended_hours` config of Alpaca broker feeder
> bugfix(archivejob): parse extended_hours config

- contrib/alpacabkfeeder/README.md
- contrib/alpacabkfeeder/alpacav2.go
- contrib/alpacabkfeeder/api/client.go
- contrib/alpacabkfeeder/api/credentials.go
- contrib/alpacabkfeeder/configs/config.go
- contrib/alpacabkfeeder/feed/worker.go
add `auth_method` config for Alpaca Broker feeder. 
Alpaca API accepts HTTP header auth or Basic auth depending on the type of ID/Secret.
> feat(alpacabkfeeder): add AuthMethod config
